"""UpdateRequestTalbe

Revision ID: 01649f63a22a
Revises: c5334fcbd16d
Create Date: 2025-05-30 11:07:48.625549

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01649f63a22a"
down_revision: Union[str, None] = "c5334fcbd16d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "warning_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("warning_flags")

    # ### end Alembic commands ###
