"""Update creditType and requestStatus tables

Revision ID: 0eeac19b4679
Revises: b68c52c72d7d
Create Date: 2025-05-29 15:12:40.230883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0eeac19b4679"
down_revision: Union[str, None] = "b68c52c72d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_types", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                sqlmodel.sql.sqltypes.AutoString(length=None),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))

    with op.batch_alter_table("request_statuses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description",
                sqlmodel.sql.sqltypes.AutoString(length=None),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_statuses", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_active")
        batch_op.drop_column("description")

    with op.batch_alter_table("credit_types", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_active")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
