"""Initial database schema with requests table

Revision ID: 17e3f08903dd
Revises:
Create Date: 2025-05-29 14:16:42.405359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "17e3f08903dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("requested_amount", sa.Float(), nullable=False),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("annual_interest_rate", sa.Float(), nullable=False),
        sa.Column(
            "credit_type",
            sa.Enum("WORKING_CAPITAL", "INVESTMENT", "CONSUMPTION", name="credittype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "DISBURSED",
                "PAID",
                "CANCELED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("approved_amount", sa.Float(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("analyst_id", sa.Uuid(), nullable=True),
        sa.Column(
            "rejection_reason",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requests_analyst_id"), ["analyst_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requests_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_requests_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requests_id"))
        batch_op.drop_index(batch_op.f("ix_requests_client_id"))
        batch_op.drop_index(batch_op.f("ix_requests_analyst_id"))

    op.drop_table("requests")
    # ### end Alembic commands ###
