"""Update Request table

Revision ID: 27fd9995217c
Revises: fea40ec61a05
Create Date: 2025-05-30 01:49:32.323538

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27fd9995217c"
down_revision: Union[str, None] = "fea40ec61a05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
