"""UpdatedNotificationUserTable

Revision ID: 2f8568db2f8c
Revises: 1053a3cbd9c8
Create Date: 2025-05-30 16:08:33.485579

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f8568db2f8c"
down_revision: Union[str, None] = "1053a3cbd9c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("read_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications_users", schema=None) as batch_op:
        batch_op.drop_column("read_at")

    # ### end Alembic commands ###
