"""Created clients profile table

Revision ID: 86895a312c9a
Revises: c4947349fb5e
Create Date: 2025-05-29 19:08:27.523470

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "86895a312c9a"
down_revision: Union[str, None] = "c4947349fb5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "address_line1",
            sqlmodel.sql.sqltypes.AutoString(length=None),
            nullable=True,
        ),
        sa.Column(
            "address_city", sqlmodel.sql.sqltypes.AutoString(length=None), nullable=True
        ),
        sa.Column(
            "address_region",
            sqlmodel.sql.sqltypes.AutoString(length=None),
            nullable=True,
        ),
        sa.Column(
            "address_postal_code",
            sqlmodel.sql.sqltypes.AutoString(length=None),
            nullable=True,
        ),
        sa.Column("annual_income", sa.Float(), nullable=True),
        sa.Column("years_of_agricultural_experience", sa.Integer(), nullable=True),
        sa.Column("has_agricultural_insurance", sa.Boolean(), nullable=True),
        sa.Column("internal_credit_history_score", sa.Float(), nullable=True),
        sa.Column("current_debt_to_income_ratio", sa.Float(), nullable=True),
        sa.Column("farm_size_hectares", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("client_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_profiles_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_profiles_user_id"))

    op.drop_table("client_profiles")
    # ### end Alembic commands ###
