"""UpdatedClientTable

Revision ID: 9124ecfd168f
Revises: de4adf374e0e
Create Date: 2025-05-30 17:29:17.801162

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9124ecfd168f"
down_revision: Union[str, None] = "de4adf374e0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sqlmodel.sql.sqltypes.AutoString(length=None), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_profiles", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
