"""Created clients profile table

Revision ID: c4947349fb5e
Revises: 9203f7a072b4
Create Date: 2025-05-29 19:06:15.289920

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c4947349fb5e"
down_revision: Union[str, None] = "9203f7a072b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "risk_assessment_details",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "purpose_description",
                sqlmodel.sql.sqltypes.AutoString(length=1000),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("applicant_contribution_amount", sa.Float(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "collateral_offered_description",
                sqlmodel.sql.sqltypes.AutoString(length=1000),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("collateral_offered_description")
        batch_op.drop_column("applicant_contribution_amount")
        batch_op.drop_column("purpose_description")
        batch_op.drop_column("risk_assessment_details")

    # ### end Alembic commands ###
