"""Update Request table

Revision ID: fea40ec61a05
Revises: d0e73d69f864
Create Date: 2025-05-30 01:19:25.959142

"""

# ruff: noqa: F401
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fea40ec61a05"
down_revision: Union[str, None] = "d0e73d69f864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collateral_value", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("number_of_dependents", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("other_income_sources", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("previous_defaults", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("previous_defaults")
        batch_op.drop_column("other_income_sources")
        batch_op.drop_column("number_of_dependents")
        batch_op.drop_column("collateral_value")

    # ### end Alembic commands ###
